"""Add src_folder, dest_folder, isMoved to FileRecord

Revision ID: 5539d7c6e86a
Revises: 72cd750a5da6
Create Date: 2024-05-25 15:55:16.212402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539d7c6e86a'
down_revision = '72cd750a5da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('src_folder', sa.String(length=256), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('dest_folder', sa.String(length=256), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('isMoved', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###

    # Set server_default back to None after data has been backfilled
    with op.batch_alter_table('file_record', schema=None) as batch_op:
        batch_op.alter_column('src_folder', server_default=None)
        batch_op.alter_column('dest_folder', server_default=None)
        batch_op.alter_column('isMoved', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_record', schema=None) as batch_op:
        batch_op.drop_column('isMoved')
        batch_op.drop_column('dest_folder')
        batch_op.drop_column('src_folder')
    # ### end Alembic commands ###
